### ISSUE TITLE
Float is a special float name

### ISSUE THREAD

**Issue by MitchTheAwesome** [PocketMine/php-build-scripts#31] opened 2016-04-03 06:06 UTC
Hi

Could someone please help me!
I'm using a mac (el capitan) and I have setup the server but every time I run it I get the text Below!
I'm using php 7.0.3 downloaded at https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/7.0.3/view 
This is really annoying and would like a solution asap

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/mitchellpescud/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by PEMapModder** [comment] 2016-04-03 08:53
Duplicate of #30

**Closed** 2016-05-02 09:19 UTC
